### ISSUE TITLE
Dashboard could not load logs

### ISSUE THREAD

**Issue by patrickjaigner** [iterize/tenta#27]
Time:
- Tested between 8:15 and 8:21 (CET)

Further Info:
- The dashboard crashed multiple times while trying to load the latest logs. Tested on systems 7 or 5.  
- All other tabs are working

Observation:
- Loading logs runs with no result (spinning loading indication)
- Exit to Log-In-Prompt 

Additional info
- In parallel, a download of the last 24h of measurement data is running

Actions to resolve the issue:
- None

**Comment by patrickjaigner** [comment]
Update 8:57:
Loading the logs works again. The download has finished in the meanwhile. A download of the last 24h currently takes >1h.

**Comment by empicano** [comment]
Adding logs to such issues helps a lot in finding the root cause. I think for this one, both server and dashboard logs would be interesting. If you [run Tenta in development](https://tenta.onrender.com/contribute) you have the logs directly in the terminal. You can find the production server logs in LogTail or DigitalOcean in your setup, and the dashboard logs in the browser console.

**Comment by dostuffthatmatters** [comment]
Server ran out of memory. Fix it by giving the server at least 512 Mb of memory. #26 will fix it too.
