### ISSUE TITLE
[User Story] Database download speed

### ISSUE THREAD

**Issue by patrickjaigner** [iterize/tenta#36]
As a system operator, I want to daily download the latest 24 hours of data in a reasonable time, so that I can start working with the data at the start of my working day.

**Comment by empicano** [comment]
Thank you for all these new issues, Patrick! You make a lot of helpful points 👍

Regarding this issue: I still think that accessing the database directly instead of going over the server is the best choice here. For some context, how much data is included in those 24 hours approximately and how long does it take to download it with our QuickFlow pipeline?

It would definitely be great to find a faster way to do this and go more in depth on it in the documentation. Off the top of my head there are three options:

- Remove/reduce the time limit for readonly queries (at ESM I've configured this via `statement_timeout` but by default there is no limit) and download in bigger chunks
- Download the data with some other tool, e.g. PostgreSQL's `COPY`, DuckDB
- Set up a read replica and run queries directly on that. You can do that in TimescaleCloud, but that should be possible locally as well (however then you need to manage a database)

To give context, we want to isolate queries for processing and downloads from the write queries to ensure that the database is always available to write new data.

This issue can be isolated pretty well and more documentation on this would make a great contribution to the project, if someone is up for it 🙂 Personally, I'd try out DuckDB first.

**Comment by patrickjaigner** [comment]
I was able to resolve the issue. The existing downloader was optimized for the air quality network which uses "receipt_timestamp" as index, while the tenta implementation is using "creation_timestamp" as the index. With a growing timescaleDB database the queries slowed down the overall download. Updating the SQL queries resolved the issue. 

Updated query for tenta implementation:
```
creation_timestamp is read from the last line of the local copy of the database
chunksize = 2**16


query = (f"""
  SELECT *
  FROM measurement
  ORDER BY creation_timestamp
  LIMIT {self.chunksize}
  """ if creation_timestamp is None else f"""
  SELECT *
  FROM measurement
  WHERE creation_timestamp > '{creation_timestamp}'
  ORDER BY creation_timestamp
  LIMIT {self.chunksize}
  """)
```

**Comment by empicano** [comment]
Thanks for reporting back! 👍
